openapi: 3.0.0
info:
  version: "1.0.0"
  title: Compass API
paths:
  /v1/auth/createAccount:
    post:
      summary: Create Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                name:
                  type: string
                profile:
                  type: string
      responses:
        '200':
          description: Account created successfully
  /v1/auth/login:
    post:
      summary: Login Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Logged in successfully
  /v1/products/register:
    post:
      summary: Add Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                expireDate:
                  type: string
                  format: date
                barCodeId:
                  type: string
                name:
                  type: string
                description:
                  type: string
                region:
                  type: string
                imageUrl:
                  type: string
                brand:
                  type: string
                category:
                  type: string
      responses:
        '200':
          description: Product added successfully
  /v1/products/getProducts:
    get:
      summary: Get Products
      responses:
        '200':
          description: Retrieved products successfully
  /v1/products/search:
    get:
      summary: Search Product
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retrieved search results successfully
  /v1/products/delete:
    post:
      summary: Delete Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Product deleted successfully
openapi: 3.0.0
info:
  version: "1.0.0"
  title: Compass API
paths:
  /v1/auth/createAccount:
    post:
      summary: Create Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                name:
                  type: string
                profile:
                  type: string
      responses:
        '200':
          description: Account created successfully
  /v1/auth/login:
    post:
      summary: Login Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Logged in successfully
  /v1/products/register:
    post:
      summary: Add Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                expireDate:
                  type: string
                  format: date
                barCodeId:
                  type: string
                name:
                  type: string
                description:
                  type: string
                region:
                  type: string
                imageUrl:
                  type: string
                brand:
                  type: string
                category:
                  type: string
      responses:
        '200':
          description: Product added successfully
  /v1/products/getProducts:
    get:
      summary: Get Products
      responses:
        '200':
          description: Retrieved products successfully
  /v1/products/search:
    get:
      summary: Search Product
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retrieved search results successfully
  /v1/products/delete:
    post:
      summary: Delete Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Product deleted successfully
